/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CodexSession {
  get conversationId(): string
  nextEvent(): Promise<string | null>
  submit(submissionJson: string): Promise<void>
  close(): Promise<void>
}

export declare class NativeCodex {
  constructor(options?: NativeCodexOptions | undefined | null)
  createConversation(options?: CreateConversationOptions | undefined | null): Promise<CodexSession>
}

export declare function cliVersion(): string

export interface ConfigOverrideEntry {
  key: string
  value: string
}

export interface CreateConversationOptions {
  overrides?: Array<ConfigOverrideEntry>
}

export interface NativeCodexOptions {
  codexHome?: string
}

export declare function version(): string
